spring.profiles.active=mysql

# application.properties
spring.application.name=smart-contact-manager
server.port=8080
spring.devtools.add-properties=true

# Mail Config
system.mail.username=Vaibhav07154@gmail.com
system.mail.password=vaibhav123
system.mail.host=smtp.gmail.com
system.mail.port=465

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


